JSON?
Sherokiel/Calculator pull request #15
Opened 2022-11-02 11:13 UTC by Sherokiel

1) Create file history.json to fix bug with no history file
2) Added message "History is empty" if history is empty
3) Add json encode
4) change history .txt to .json.

2022-11-03 13:15 UTC, DenTray requested changes

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +    {
```suggestion
    if($history == null) {
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +if (!$history == NULL) {
```suggestion
if ($history !== null) {
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +    $history = json_decode($history);
```suggestion
    $history = json_decode($history, true);
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +    }
please move it to the start on the program

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +    array_push($history,"{$argument1} {$command} {$argument2}  =  {$result}" );
```suggestion
    array_push($history, "{$argument1} {$command} {$argument2} = {$result}");
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +function execute_system_command($command,$history)
please try to use global history variable without passing it to the method

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +    }
please move it to the start of the program

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +    array_push($history, "{$argument1} {$command} {$argument2}  =  {$result}" );
```suggestion
    array_push($history, "{$argument1} {$command} {$argument2} = {$result}");
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +
```suggestion
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +        file_put_contents('history.json', $history);
```suggestion
            $history = json_encode($history);
            file_put_contents('history.json', $history);
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +
```suggestion
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +    if ($history == null) {
```suggestion
    if ($history === null) {
```

2022-11-03 13:15 UTC, DenTray commented on Calculator.php
> +            info($value);
```suggestion
        foreach ($history as $value) {
            info($value);
        }
```

2022-11-03 16:14 UTC, DenTray requested changes

2022-11-03 16:14 UTC, DenTray commented on Calculator.php
> +    $history = [ ];
```suggestion
    $history = [];
```

2022-11-03 16:14 UTC, DenTray commented on Calculator.php
> +if ($history != null) {
```suggestion
} else {
```

2022-11-03 16:14 UTC, DenTray commented on Calculator.php
> +if ($history == null) {
```suggestion
if ($history === null) {
```

2022-11-03 16:14 UTC, DenTray commented on Calculator.php
> +function execute_system_command($command,$history)
not fixed

2022-11-03 16:14 UTC, DenTray commented on Calculator.php
> +
not fixed

2022-11-04 05:22 UTC, DenTray requested changes

2022-11-04 05:22 UTC, DenTray commented on Calculator.php
> +
not fixed again

2022-11-04 05:55 UTC, DenTray requested changes

2022-11-04 05:55 UTC, DenTray commented on Calculator.php
> +Function show_history($history)
```suggestion
function show_history($history)
```

2022-11-04 05:55 UTC, DenTray commented on Calculator.php
> +
and again

2022-11-04 06:09 UTC, DenTray approved these changes

2022-11-04 06:09 UTC, merged

2022-11-04 16:12 UTC, netherpyro commented
Жесть
Ctrl + Alt + L не выучил 😄?