If u say it not, what u want from me i go for beer
Sherokiel/Calculator pull request #17
Opened 2022-11-04 16:04 UTC by Sherokiel

2022-11-04 16:10 UTC, netherpyro approved these changes
Go out and drink

2022-11-04 16:17 UTC, Sherokiel commented
I cant Master say i want learn !

2022-11-04 16:28 UTC, Sherokiel commented
Причем он тебя же процитировал XD говорит "Как сказал Миша , пока не сделаешь никакого пиваXD "

2022-11-05 09:06 UTC, DenTray requested changes

2022-11-05 09:06 UTC, DenTray commented on Calculator.php
> +    $history[] = ["date"=>"{$date}", "function" => "({$argument1} {$command} {$argument2} = {$result})"];
```suggestion
    $history[] = [
        'date' => $date,
        'function' => "{$argument1} {$command} {$argument2} = {$result}"
    ];
```

2022-11-05 09:06 UTC, DenTray commented on Calculator.php
>          foreach ($history as $value) {
```suggestion
        foreach ($history as $historyItem) {
```

2022-11-05 09:06 UTC, DenTray commented on Calculator.php
> +            info("Date: {$date} function: {$function} ");
```suggestion
            extract($value);
            info("Date: {$historyItem['date']} function: {$historyItem['function']} ");
```

2022-11-05 09:06 UTC, DenTray commented on Calculator.php
> +$date = date('F j, Y,G:i');
let's use `YY "/" MM "/" DD` date fomat, it will be helpful for the future

2022-11-05 10:52 UTC, DenTray approved these changes

2022-11-05 10:52 UTC, merged