v1.13.01
Sherokiel/Calculator pull request #21
Opened 2022-11-11 06:56 UTC by Sherokiel

WELCOME

2022-11-11 07:20 UTC, DenTray requested changes

2022-11-11 07:20 UTC, DenTray commented on Calculator.php
> +welcome(' Wellcome to the calculataor app!','Print "help" to learn more about the app');
```suggestion
welcome('Wellcome to the calculataor app!', 'Print "help" to learn more about the app');
```

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +function welcome($msg1,$msg2)
also let's move it to the console_helpers library

```suggestion
function info_box(...$lines)
```

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +    $length = 45;
let's get lenght as a max lenght of the one of passed line

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +    $maxStrings = 8;
```suggestion
    $maxStrings = count($lines);
```

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +
```suggestion
```

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +            }
please use pad str for it

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +            {
```suggestion
            switch ($string) {
```

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +                    break;
```suggestion

                    break;
```

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +                    break;
```suggestion

                    break;
```

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +            echo "*" . PHP_EOL;
generate string to the variable and use info helper to show it

2022-11-11 07:20 UTC, DenTray commented on libraries/helpers.php
> +        $string++;
```suggestion

        $string++;
```

2022-11-11 10:45 UTC, netherpyro commented
поздравляю с 21 ПРом 🎉

2022-11-11 10:49 UTC, Sherokiel commented
Хаха))  спасибо

2022-11-11 11:25 UTC, DenTray requested changes

2022-11-11 11:25 UTC, DenTray commented on Calculator.php
>              break;
```suggestion
            return $argument1 + $argument2;
```

2022-11-11 11:25 UTC, DenTray commented on libraries/console_helpers.php
> +    }
```suggestion
    $lineLengths = array_map(function () {
        return strlen($maxLines);
    }, $lines);
```

2022-11-11 11:25 UTC, DenTray commented on libraries/console_helpers.php
> +    info (str_pad('*', $length, '*'), 1);
```suggestion
    info(str_repeat('*', $length), 1);
```

2022-11-11 11:25 UTC, DenTray commented on libraries/console_helpers.php
> +    info (str_pad('*', $length, '*'), 1);
let's also move it to the separate console helper `write_symbol_line($length, $sybmol)`

2022-11-12 07:37 UTC, DenTray requested changes

2022-11-12 07:37 UTC, DenTray commented on Calculator.php
> +
```suggestion
```

2022-11-12 07:37 UTC, DenTray commented on Calculator.php
> +
```suggestion
```

2022-11-12 07:37 UTC, DenTray commented on Calculator.php
> -
please revert empty line

2022-11-12 07:37 UTC, DenTray commented on Calculator.php
> -
please revert empty line

2022-11-12 07:37 UTC, DenTray commented on libraries/console_helpers.php
> +    $lineLengths = array_map(function ($maxLines) {
```suggestion
    $lineLengths = array_map(function ($line) {
```

2022-11-12 07:37 UTC, DenTray commented on libraries/console_helpers.php
> +    $length = max($lineLengths) + 6;
let's move 6 to the variable, defining in the start of the function

2022-11-12 07:37 UTC, DenTray commented on libraries/console_helpers.php
> +    foreach ($lines as $msg) {
```suggestion
    foreach ($lines as $line) {
```

2022-11-12 07:37 UTC, DenTray commented on libraries/console_helpers.php
> +    write_symbol_line($length, '*');
```suggestion

    write_symbol_line($length, '*');
```

2022-11-12 07:50 UTC, DenTray approved these changes

2022-11-12 07:51 UTC, merged